export const STORAGE_FILL_COLOR = "PPT_FILL_COLOR";
export const STORAGE_SHADOW_COLOR = "STORAGE_SHADOW_COLOR";
export const STORAGE_BORDER_COLOR = "PPT_BORDER_COLOR";
export const STORAGE_FLIP = "PPT_FLIP";
export const STORAGE_FONT_COLOR = "PPT_FONT_COLOR";
